<?php

/**
 * BaseStackappCategoryAffiliate
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $category_id
 * @property integer $affiliate_id
 * @property StackappCategory $StackappCategory
 * @property StackappAffiliate $StackappAffiliate
 * 
 * @method integer                   getCategoryId()        Returns the current record's "category_id" value
 * @method integer                   getAffiliateId()       Returns the current record's "affiliate_id" value
 * @method StackappCategory          getStackappCategory()  Returns the current record's "StackappCategory" value
 * @method StackappAffiliate         getStackappAffiliate() Returns the current record's "StackappAffiliate" value
 * @method StackappCategoryAffiliate setCategoryId()        Sets the current record's "category_id" value
 * @method StackappCategoryAffiliate setAffiliateId()       Sets the current record's "affiliate_id" value
 * @method StackappCategoryAffiliate setStackappCategory()  Sets the current record's "StackappCategory" value
 * @method StackappCategoryAffiliate setStackappAffiliate() Sets the current record's "StackappAffiliate" value
 * 
 * @package    stackapp_v2.0
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseStackappCategoryAffiliate extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('stackapp_category_affiliate');
        $this->hasColumn('category_id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             ));
        $this->hasColumn('affiliate_id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('StackappCategory', array(
             'local' => 'category_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('StackappAffiliate', array(
             'local' => 'affiliate_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));
    }
}