<?php

/**
 * BaseStackappAffiliate
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $url
 * @property string $email
 * @property string $token
 * @property boolean $is_active
 * @property Doctrine_Collection $StackappCategories
 * @property Doctrine_Collection $StackappCategoryAffiliate
 * 
 * @method string              getUrl()                       Returns the current record's "url" value
 * @method string              getEmail()                     Returns the current record's "email" value
 * @method string              getToken()                     Returns the current record's "token" value
 * @method boolean             getIsActive()                  Returns the current record's "is_active" value
 * @method Doctrine_Collection getStackappCategories()        Returns the current record's "StackappCategories" collection
 * @method Doctrine_Collection getStackappCategoryAffiliate() Returns the current record's "StackappCategoryAffiliate" collection
 * @method StackappAffiliate   setUrl()                       Sets the current record's "url" value
 * @method StackappAffiliate   setEmail()                     Sets the current record's "email" value
 * @method StackappAffiliate   setToken()                     Sets the current record's "token" value
 * @method StackappAffiliate   setIsActive()                  Sets the current record's "is_active" value
 * @method StackappAffiliate   setStackappCategories()        Sets the current record's "StackappCategories" collection
 * @method StackappAffiliate   setStackappCategoryAffiliate() Sets the current record's "StackappCategoryAffiliate" collection
 * 
 * @package    stackapp_v2.0
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseStackappAffiliate extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('stackapp_affiliate');
        $this->hasColumn('url', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('email', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'unique' => true,
             'length' => 255,
             ));
        $this->hasColumn('token', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('is_active', 'boolean', null, array(
             'type' => 'boolean',
             'notnull' => true,
             'default' => 0,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('StackappCategory as StackappCategories', array(
             'refClass' => 'StackappCategoryAffiliate',
             'local' => 'affiliate_id',
             'foreign' => 'category_id'));

        $this->hasMany('StackappCategoryAffiliate', array(
             'local' => 'id',
             'foreign' => 'affiliate_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}