<?php

/**
 * BaseStackappCategory
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $name
 * @property Doctrine_Collection $StackappJobs
 * @property Doctrine_Collection $StackappAffiliates
 * @property Doctrine_Collection $StackappCategoryAffiliate
 * 
 * @method string              getName()                      Returns the current record's "name" value
 * @method Doctrine_Collection getStackappJobs()              Returns the current record's "StackappJobs" collection
 * @method Doctrine_Collection getStackappAffiliates()        Returns the current record's "StackappAffiliates" collection
 * @method Doctrine_Collection getStackappCategoryAffiliate() Returns the current record's "StackappCategoryAffiliate" collection
 * @method StackappCategory    setName()                      Sets the current record's "name" value
 * @method StackappCategory    setStackappJobs()              Sets the current record's "StackappJobs" collection
 * @method StackappCategory    setStackappAffiliates()        Sets the current record's "StackappAffiliates" collection
 * @method StackappCategory    setStackappCategoryAffiliate() Sets the current record's "StackappCategoryAffiliate" collection
 * 
 * @package    stackapp_v2.0
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseStackappCategory extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('stackapp_category');
        $this->hasColumn('name', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('StackappJob as StackappJobs', array(
             'local' => 'id',
             'foreign' => 'category_id'));

        $this->hasMany('StackappAffiliate as StackappAffiliates', array(
             'refClass' => 'StackappCategoryAffiliate',
             'local' => 'category_id',
             'foreign' => 'affiliate_id'));

        $this->hasMany('StackappCategoryAffiliate', array(
             'local' => 'id',
             'foreign' => 'category_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $i18n0 = new Doctrine_Template_I18n(array(
             'fields' => 
             array(
              0 => 'name',
             ),
             ));
        $sluggable1 = new Doctrine_Template_Sluggable(array(
             'fields' => 
             array(
              0 => 'name',
             ),
             'uniqueBy' => 
             array(
              0 => 'name',
             ),
             ));
        $i18n0->addChild($sluggable1);
        $this->actAs($timestampable0);
        $this->actAs($i18n0);
    }
}