<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2013/07/08 11:46:31

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:host=localhost;dbname=stackapp_v2.0',
  'username' => 'root',
  'password' => NULL,
  'name' => 'doctrine',
)),);
