<?php

/**
 * StackappCategoryAffiliateTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class StackappCategoryAffiliateTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object StackappCategoryAffiliateTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('StackappCategoryAffiliate');
    }
}