<?php

/**
 * StackappCategoryTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class StackappCategoryTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object StackappCategoryTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('StackappCategory');
    }
}