<?php

/**
 * StackappJobTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class StackappJobTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object StackappJobTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('StackappJob');
    }
}