<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2013/07/08 21:49:56

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:host=localhost;dbname=stackapp_v2',
  'username' => 'root',
  'password' => 407,
  'name' => 'doctrine',
)),);
